#!/bin/bash

TAG_VERSION=`git tag --sort -"v:refname" | head -n 1`

docker build --build-arg VCS_REF=${SOURCE_COMMIT:0:7} \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -t $IMAGE_NAME -t $DOCKER_REPO:$TAG_VERSION .
