name: Check get_iplayer version

on:
  workflow_dispatch:
  schedule:
    - cron: "11 6 * * *"

jobs:
  check_version:
    runs-on: default-linux
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Check get_iplayer release
        id: iplayerversion
        run: |
          NEW_VER=`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/get-iplayer/get_iplayer/releases?per_page=1 2>/dev/null | jq -r '.[] | .tag_name'`
          echo "iplayerver=$NEW_VER" >> $GITHUB_OUTPUT
      - name: Check local repo release
        id: localversion
        run: |
          CUR_VER="$(git tag --sort v:refname | tail -n 1)"
          echo "localver=$CUR_VER" >> $GITHUB_OUTPUT
    outputs:
      iplayerver: ${{ steps.iplayerversion.outputs.iplayerver }}
      localver: ${{ steps.localversion.outputs.localver }}

  update_iplayer:
    runs-on: default-linux
    needs: check_version
    if: ${{ needs.check_version.outputs.iplayerver != needs.check_version.outputs.localver && needs.check_version.outputs.iplayerver != '' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Update Dockerfile
        id: update
        run: |
          sed -i -E "s/IPLAYER_VERSION=v[0-9]+\.[0-9]+/IPLAYER_VERSION=${{ needs.check_version.outputs.iplayerver }}/g" Dockerfile*
      - name: Commit and tag
        uses: EndBug/add-and-commit@v9
        with:
          message: "Release ${{ needs.check_version.outputs.iplayerver }}"
          add: "Dockerfile*"
          tag: ${{ needs.check_version.outputs.iplayerver }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.check_version.outputs.iplayerver }}
          token: ${{ secrets.PAT }}
